
name: Build

on: [push, pull_request]

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install build-essential git make cmake autoconf automake pkg-config
        shell: bash
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run CAKE
        run: dotnet run --project ./build/Build.csproj
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RUNTIME_URL: "${{ env.ACTIONS_RUNTIME_URL }}"
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    needs: [ build ]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run CAKE
        run: dotnet run --project ./build/Build.csproj -- --target=Package --libraryname=FreeImage --licensepath=freeimage/license-fi.txt
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_RUNTIME_URL: "${{ env.ACTIONS_RUNTIME_URL }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: 3.18.0
      - name: Make a release
        uses: ncipollo/release-action@v1
        with:
          name: 'MonoGame.Library.FreeImage ${{ github.ref_name }}'
          tag: ${{ github.ref_name }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: "bin/Release/*.nupkg"
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_type == 'tag'

